"use strict";
var someValue = 'this is a string';
var strLength = someValue.length;
console.log(strLength);
var strLength2 = someValue.length;
console.log(strLength2);
var str = '1';
var str2 = str;
var str3 = str2;
var str4 = str;
console.log(str, str2, str3);
