"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var num1 = 10;
var num2 = 3;
var res = 0;
res = num1 + num2;
console.log("+ : " + res);
res = num1 - num2;
console.log("- : " + res);
res = num1 * num2;
console.log("* : " + res);
res = num1 / num2;
console.log("/ : " + res);
res = num1 % num2;
console.log("% : " + res);
