"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var num1 = 10;
var num2 = 3;
console.log("num1 == num2 " + (num1 == num2));
console.log("num1 != num2 " + (num1 != num2));
console.log("num1 > num2 " + (num1 > num2));
console.log("num1 >= num2 " + (num1 >= num2));
console.log("num1 < num2 " + (num1 < num2));
console.log("num1 <= num2 " + (num1 <= num2));
