SELECT * FROM EMP; -- EMP 테이블의 모든 컬럼 조회
SELECT * FROM TAB; -- 모든 TAB 목록 조회
SELECT LOC FROM DEPT; -- DEPT 테이블의 LOC 컬럼 조회
SELECT ENAME, SAL FROM EMP; -- EMP 테이블의 ENAME, SAL 컬럼 조회
SELECT EMPNO, ENAME, SAL * 1.1 FROM EMP; -- EMP 테이블의 EMPNO, ENAME, SAL의 1.1 배수 조회
SELECT ENAME, SAL / 2 FROM EMP; -- EMP 테이블의 ENAME, SAL의 2분의 1배수 조회
SELECT EMPNO AS 사번, ENAME AS 성명, SAL AS 급여 FROM EMP; -- Alias (AS) 문으로 별칭 지정
SELECT DNAME 부서이름, LOC 주소지 FROM DEPT; -- AS 생략 가능
DESC EMP;
SELECT EMPNO, ENAME, SAL, COMM FROM EMP;
SELECT EMPNO, ENAME, SAL, COMM, COMM + 100 FROM EMP;

-- NULL 연산 함수 NVL(), NVL(컬럼명, 기본값)
SELECT EMPNO, ENAME, COMM, NVL(COMM, 0) FROM EMP;
-- NULL 판별 함수 NVL2(컬럼명, A, B)
-- NULL 이면 B 아니면 A를 출력
SELECT EMPNO, ENAME, COMM, NVL2(COMM, 1, 0) FROM EMP;

-- 연결 연산자 ||
-- 문자열을 연결하여 표시
SELECT ENAME || JOB AS "이름 직업" FROM EMP;
SELECT ENAME || SAL AS "사원월급" FROM EMP;
SELECT ENAME || '의 직급은 ' || JOB || '이다' AS "사원별 직급" FROM EMP;
SELECT ENAME || '의 월급은 ' || SAL || '이다' AS "사원별 월급" FROM EMP;

SELECT * FROM EMP;
DESC EMP;
SELECT ENAME, SAL * 2 FROM EMP;
SELECT ENAME, SAL * 2 AS "인상된 월급" FROM EMP;

-- DISTINCT 는 중복값을 한 번만 출력합니다.
SELECT JOB FROM EMP;
SELECT DISTINCT JOB FROM EMP;

SELECT EMPNO, ENAME FROM EMP;

SELECT ENAME
FROM EMP
WHERE ENAME = 'SMITH';

DESC DEPT;

SELECT EMPNO, ENAME, JOB, DEPTNO
FROM EMP
WHERE DEPTNO = 30;

SELECT *
FROM EMP
WHERE ENAME = 'JAMES';

SELECT * FROM DEPT;

SELECT DNAME
FROM DEPT
WHERE LOC = 'DALLAS';

SELECT DNAME
FROM DEPT
WHERE LOC = 'dallas';

SELECT EMPNO, ENAME, JOB, DEPTNO
FROM EMP
WHERE 'SALESMAN' = JOB;

SELECT * FROM EMP;
SELECT EMPNO, ENAME, JOB, DEPTNO
FROM EMP
WHERE HIREDATE = '81/11/17';

SELECT EMPNO, ENAME, SAL FROM EMP WHERE SAL <= 1000;
SELECT * FROM EMP WHERE JOB != 'SALESMAN';

SELECT EMPNO, ENAME, SAL FROM EMP WHERE SAL BETWEEN 1000 AND 2000;
SELECT EMPNO, ENAME, SAL FROM EMP WHERE EMPNO IN (7839, 7844, 7876);
SELECT EMPNO, ENAME, SAL FROM EMP WHERE ENAME IN ('SMITH', 'JONES');

SELECT EMPNO, ENAME, COMM FROM EMP WHERE COMM IS NULL;

SELECT EMPNO, ENAME, JOB FROM EMP WHERE MGR IS NULL;
SELECT * FROM EMP WHERE MGR IS NOT NULL;

-- 다중 리스트
SELECT * FROM EMP WHERE (JOB, DEPTNO) IN (('MANAGER', 20), ('CLERK', 30));

SELECT EMPNO, ENAME, JOB, SAL FROM EMP WHERE JOB = 'SALESMAN' AND SAL >= 1500;
SELECT EMPNO, ENAME, JOB, SAL FROM EMP WHERE JOB = 'SALESMAN' OR SAL >= 1500;
