















DESC TB_STUDENT;
UPDATE TB_STUDENT
SET STUDENT_ADDRESS = '서울시 종로구 숭인동 181-21'
WHERE STUDENT_NO = 'A413042';

SELECT STUDENT_ADDRESS
FROM TB_STUDENT
WHERE STUDENT_NO = 'A413042';

ROLLBACK;

SELECT *
FROM TB_STUDENT
WHERE STUDENT_NO = 'A413042';

UPDATE TB_STUDENT
SET STUDENT_SSN = SUBSTR(STUDENT_SSN, 1, 6);

SELECT *
FROM TB_STUDENT;

ROLLBACK;

DESC TB_GRADE;

DELETE FROM TB_GRADE
WHERE STUDENT_NO IN (
    SELECT STUDENT_NO
    FROM TB_STUDENT
    WHERE ABSENCE_YN = 'Y'
);

ROLLBACK;

DROP TABLE DEF_TABLE;
DROP TABLE DEF_TABLE2;

CREATE TABLE DEF_TABLE(
    NUM NUMBER(2),
    WRITEDAY DATE DEFAULT SYSDATE
);

INSERT INTO DEF_TABLE(NUM)
VALUES(1);

SELECT * FROM DEF_TABLE;

-- 의학과 김명훈 학생의 2005년도 1학기 '피부생리학' 점수가 잘못되어
-- 정정해야 한다.
-- 해당 과목의 학점을 3.5로 변경 시키시오.

SELECT STUDENT_NO
FROM TB_STUDENT
WHERE STUDENT_NAME = '김명훈'
    AND DEPARTMENT_NO = (
        SELECT DEPARTMENT_NO
        FROM TB_DEPARTMENT
        WHERE DEPARTMENT_NAME = '의학과'
    );

SELECT CLASS_NO
FROM TB_CLASS
WHERE CLASS_NAME = '피부생리학';

UPDATE TB_GRADE
SET POINT = 3.5
WHERE TERM_NO = 200501 AND
    STUDENT_NO = (
        SELECT STUDENT_NO
        FROM TB_STUDENT S
        JOIN TB_DEPARTMENT D
        ON S.DEPARTMENT_NO = D.DEPARTMENT_NO
        WHERE DEPARTMENT_NAME = '의학과'
            AND STUDENT_NAME = '김명훈'
    ) AND CLASS_NO = (
        SELECT CLASS_NO
        FROM TB_CLASS
        WHERE CLASS_NAME = '피부생리학'
    );

CREATE TABLE PK_TAB1(
    ID NUMBER(2) CONSTRAINT PK_TAB1_ID_PK PRIMARY KEY,
    NAME VARCHAR2(10)
);

DESC PK_TAB1;

SELECT *
FROM USER_CONS_COLUMNS
WHERE TABLE_NAME = 'PK_TAB1';

DROP TABLE PK_TAB2;

CREATE TABLE PK_TAB2(
    ID NUMBER(2),
    NAME VARCHAR2(10),
    CONSTRAINT PK_TAB2_ID_PK PRIMARY KEY(ID)
);

SELECT *
FROM USER_CONS_COLUMNS
WHERE TABLE_NAME = 'PK_TAB2';

CREATE TABLE SAWON1(
    S_NO NUMBER(2),
    S_NAME VARCHAR2(10) NOT NULL,
    S_EMAIL VARCHAR2(20)
        CONSTRAINT SAWON_S_EMAIL_UK UNIQUE
);

INSERT INTO SAWON1
VALUES(1, 'WOOZYA', 'ABC@ABC.COM');

CREATE TABLE SAWON7(
    S_NO NUMBER(2),
    S_NAME VARCHAR2(10),
    S_SAL NUMBER(10)
        CONSTRAINT SAWON7_S_SAL_CK CHECK(S_SAL < 500)
);

INSERT INTO SAWON7
VALUES(1, 'WOOZYA', 300);

INSERT INTO SAWON7
VALUES(1, 'WOOZYA', 600);

CREATE TABLE DEPT_P(
    DEPTNO NUMBER(2)
        CONSTRAINT DEPT_C_DEPTNO_PK PRIMARY KEY,
    DNAME VARCHAR2(10),
    LOC VARCHAR2(10)
);

CREATE TABLE EMP_C(
    EMPNO NUMBER(4)
        CONSTRAINT EMP_C_EMPNO_PK PRIMARY KEY,
    ENAME VARCHAR2(10),
    SAL NUMBER(10),
    DEPTNO NUMBER(2) -- DEPT_P를 참조하는 외래키
        CONSTRAINT EMP_C_DEPTNO_FK
        REFERENCES DEPT_P(DEPTNO)
);

INSERT INTO DEPT_P VALUES(10, '인사', '서울');
INSERT INTO DEPT_P VALUES(20, '경리', '부산');
INSERT INTO DEPT_P VALUES(30, '관리', '대구');

INSERT INTO EMP_C
VALUES(1111, 'WOOZYA', 2000, 40);

DROP TABLE EMP_C;