DESC TB_DEPARTMENT;

SELECT DEPARTMENT_NAME AS "학과 명", CATEGORY AS 계열 FROM TB_DEPARTMENT;
SELECT DEPARTMENT_NAME || '의 정원은 ' || CAPACITY || '입니다.' "학과별 정원" FROM TB_DEPARTMENT;

SELECT STUDENT_NAME FROM TB_STUDENT WHERE DEPARTMENT_NO = 001 AND ABSENCE_YN = 'Y';

SELECT EMPNO, ENAME, JOB FROM EMP WHERE ENAME LIKE 'A%';
SELECT EMPNO, ENAME, JOB FROM EMP WHERE ENAME LIKE '%T%';
SELECT EMPNO, ENAME, JOB FROM EMP WHERE ENAME LIKE '_L%';

SELECT ENAME, JOB, SAL, COMM
FROM EMP
WHERE (JOB = 'CLERK' OR JOB = 'ANALYST')
AND COMM IS NULL
AND SAL >= 1000
AND SAL <= 3000;

SELECT EMPNO, ENAME, HIREDATE
FROM EMP
ORDER BY HIREDATE; -- 기본으로 오름차순

SELECT EMPNO, ENAME, HIREDATE
FROM EMP
ORDER BY HIREDATE DESC; -- 내림차순

DESC EMP;

SELECT ENAME, SAL
FROM EMP
ORDER BY SAL DESC;

SELECT EMPNO, ENAME, SAL * 12 ANNUAL
FROM EMP
ORDER BY 3;

SELECT EMPNO, ENAME, SAL
FROM EMP
ORDER BY SAL DESC, EMPNO;

SELECT STUDENT_NAME FROM TB_STUDENT WHERE STUDENT_NO IN('A513079', 'A513091', 'A513110');

SELECT DEPTNO, INITCAP(DNAME), INITCAP(LOC)
FROM DEPT;

SELECT EMPNO, ENAME, LOWER(JOB), DEPTNO
FROM EMP
WHERE LOWER(ENAME) = 'scott';

SELECT EMPNO, ENAME, JOB, DEPTNO
FROM EMP
WHERE ENAME = UPPER('scott');

SELECT EMPNO, ENAME, JOB, CONCAT(ENAME, JOB)
FROM EMP
WHERE EMPNO = 7369;

SELECT EMPNO, ENAME, JOB, ENAME || JOB "이름 업무"
FROM EMP
WHERE EMPNO = 7369;

SELECT ENAME, LPAD(ENAME, 15, '*'), SAL, LPAD(SAL, 10, '*')
FROM EMP
WHERE DEPTNO = 10;

SELECT ENAME, RPAD(ENAME, 15, '*'), SAL, RPAD(SAL, 10, '*')
FROM EMP
WHERE DEPTNO = 10;

SELECT SUBSTR(ENAME, 1, 2) FROM EMP;

SELECT EMPNO, ENAME, LENGTH(ENAME) 이름길이, SAL, LENGTH(SAL) 월급자릿수
FROM EMP
WHERE DEPTNO = 20;

SELECT EMPNO, ENAME, LENGTH(ENAME) 이름길이, SAL, LENGTH(SAL)
FROM EMP
WHERE DEPTNO = 20
ORDER BY 이름길이 DESC;

SELECT HIREDATE FROM EMP;

SELECT EMPNO, ENAME, CONCAT(SUBSTR(HIREDATE, 1, 2), '년도 입사') AS 입사년도
FROM EMP;

SELECT SUBSTR('000101-3123456', 8, 1) FROM DUAL;
SELECT SUBSTR('000101-3123456', 1, 2) 출생년도 FROM DUAL;
SELECT SUBSTR('000101-3123456', 8) "8번째 이후" FROM DUAL;

SELECT RPAD(SUBSTR('000101-3123456', 1, 8), 14, '*') 주민번호 FROM DUAL;
SELECT REPLACE('000101-3123456', SUBSTR('000101-3123456', 9), '******') FROM DUAL;
SELECT ENAME, JOB, REPLACE(JOB, 'A', '$') FROM EMP;

SELECT ENAME, JOB, LTRIM(JOB, 'A'), SAL, LTRIM(SAL, 1) FROM EMP;
SELECT ENAME, JOB, RTRIM(JOB, 'T'), SAL, RTRIM(SAL, 0) FROM EMP;
SELECT EMPNO, JOB, TRIM(LEADING 'S' FROM JOB) AS LEADING, TRIM(TRAILING 'N' FROM JOB) AS TRAILING
FROM EMP
WHERE EMPNO = 7844;

SELECT SYSDATE FROM DUAL;
SELECT LTRIM('     MILLER     '), LENGTH(LTRIM('     MILLER     ')) FROM DUAL;
SELECT LENGTH(TRIM(' HELLO A ')) FROM DUAL;

SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY >= 20 AND CAPACITY <= 30;

SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT;

SELECT * FROM TB_STUDENT;

SELECT CEIL(10.1) FROM DUAL; -- CEIL() 올림 함수
SELECT FLOOR(10.7) FROM DUAL; -- FLOOR() 내림 함수
SELECT MOD(10, 3) FROM DUAL; -- MOD() 나머지 함수

SELECT SAL, MOD(SAL, 30)
FROM EMP
WHERE DEPTNO = 10;

SELECT ROUND(4567.678), ROUND(4567.678, 0), ROUND(4567.678, 2), ROUND(4567.678, -2)
FROM DUAL;




