"use strict";
var list = ['aaa', 'bbb', 'ccc'];
list[3] = 'ddd';
console.log(list);
var list2 = [1, 2, 3];
list2[3] = 100;
console.log(list2);
// const ageList: age = {};
var ageList = {};
ageList['one'] = 100;
ageList['two'] = 200;
ageList['three'] = 300;
console.log(ageList);
